FROM  nvcr.io/nvidia/pytorch:23.05-py3
# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
#COPY requirements.txt /tmp/pip-tmp/
#RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt && rm -rf /tmp/pip-tmp

# COPY ./project /workspace/project
# ENTRYPOINT ["python"]
#CMD ["/workspace/project/main.py"] 
